data_source snowflake:  
    type: snowflake
    account: pa98452.central-india.azure
    username: raju
    password: Dhiyaguru@465577
    role: accountadmin
    database: data
    warehouse: compute_wh
    schema: schema
    threads: 10
    client_session_keep_alive: False
  soda_cloud:
  host: cloud.soda.io
  api_key_id: 0c1708b7-30fd-41c0-8409-8f531fd58eff
  api_key_secret: ETRvLV28YJstJYGPtBLWSYQW2bf14Y_Tup7lv44x8b0IUjWOGpdRsQ
