data_source snowflake:  
    type: snowflake
    account: pa98452.central-india.azure
    username: raju
    password: Dhiyaguru@465577
    role: accountadmin
    database: SNOWFLAKE_SAMPLE_DATA
    warehouse: compute_wh
    schema: TPCH_SF1
    threads: 10
    client_session_keep_alive: False
  soda_cloud:
  host: cloud.soda.io
  api_key_id: 75f02b82-989f-475a-ae79-51cf7b58bad4
  api_key_secret: 4s8lPrQlmFgTXR-BkKkvR6h6qp0uUCXs0ZAILzPShJCV_rXZ_eGDZg
