- name: Perform Soda Scan
  uses: sodadata/soda-github-action@v1
  env:
    SODA_CLOUD_API_KEY: ${{ secrets.SODA_CLOUD_API_KEY }}
    SODA_CLOUD_API_SECRET: ${{ secrets.SODA_CLOUD_API_SECRET }}
    POSTGRES_USERNAME: ${{ secrets.POSTGRES_USERNAME }}
    POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
  with:
    soda_library_version: v1.0.4
    data_source: snowflake1
    configuration: .soda/configuration.yaml
    checks: .soda/checks.yaml
